import type { StaffMember, Task } from "./types"

// Sample data for the application
// In a real application, this would come from a database

export const staffMembers: StaffMember[] = [
  { id: 1, name: "Gais Ahmed", role: "Flight Operations Specialist", userRole: "user" },
  { id: 2, name: "Hassan Aiman", role: "Navigation and Route Planner", userRole: "user" },
  { id: 3, name: "Aminath Akmal", role: "Flight Operations Engineer", userRole: "user" },
  { id: 4, name: "Zaid Asad", role: "Head of Flight Technical", userRole: "manager" },
  { id: 5, name: "Haail Hassan", role: "Flight Operations Manager", userRole: "manager" },
]

export const tasks: Task[] = [
  {
    id: 1,
    title: "Design User Dashboard",
    description: "Create wireframes and mockups for the main user dashboard.",
    assigneeIds: [3],
    startDate: "2025-03-10",
    endDate: "2025-03-14",
    status: "in-progress",
    completion: 60,
    complexity: 4,
    workload: 3,
    isExpanded: true,
    updates: [
      {
        id: 101,
        text: "Completed initial wireframes, starting on high-fidelity mockups.",
        timestamp: "2025-03-11T14:30:00Z",
        userId: 3,
      },
    ],
    subtasks: [
      {
        id: 101,
        parentId: 1,
        title: "Research UI patterns",
        description: "Research modern UI patterns for dashboard design",
        assigneeIds: [3],
        startDate: "2025-03-10",
        endDate: "2025-03-11",
        status: "completed",
        completion: 100,
      },
      {
        id: 102,
        parentId: 1,
        title: "Create wireframes",
        description: "Create low-fidelity wireframes for dashboard",
        assigneeIds: [3],
        startDate: "2025-03-11",
        endDate: "2025-03-12",
        status: "completed",
        completion: 100,
      },
      {
        id: 103,
        parentId: 1,
        title: "Design high-fidelity mockups",
        description: "Create detailed mockups based on approved wireframes",
        assigneeIds: [3],
        startDate: "2025-03-12",
        endDate: "2025-03-14",
        status: "in-progress",
        completion: 40,
      },
    ],
  },
  {
    id: 2,
    title: "Implement Authentication API",
    description: "Develop the backend API for user authentication and authorization.",
    assigneeIds: [2, 5],
    startDate: "2025-03-08",
    endDate: "2025-03-15",
    status: "in-progress",
    completion: 75,
    complexity: 5,
    workload: 4,
    isExpanded: false,
    updates: [
      {
        id: 102,
        text: "Completed JWT implementation, working on role-based access control.",
        timestamp: "2025-03-10T09:15:00Z",
        userId: 2,
      },
    ],
    subtasks: [
      {
        id: 201,
        parentId: 2,
        title: "Design API endpoints",
        description: "Define API endpoints and request/response formats",
        assigneeIds: [2],
        startDate: "2025-03-08",
        endDate: "2025-03-09",
        status: "completed",
        completion: 100,
      },
      {
        id: 202,
        parentId: 2,
        title: "Implement JWT authentication",
        description: "Implement JWT-based authentication system",
        assigneeIds: [2, 5],
        startDate: "2025-03-09",
        endDate: "2025-03-12",
        status: "completed",
        completion: 100,
      },
      {
        id: 203,
        parentId: 2,
        title: "Implement role-based access control",
        description: "Add RBAC to API endpoints",
        assigneeIds: [2],
        startDate: "2025-03-12",
        endDate: "2025-03-15",
        status: "in-progress",
        completion: 50,
      },
    ],
  },
  {
    id: 3,
    title: "Responsive Layout Implementation",
    description: "Implement responsive layouts for all major pages of the application.",
    assigneeIds: [1, 3],
    startDate: "2025-03-12",
    endDate: "2025-03-18",
    status: "in-progress",
    completion: 30,
    complexity: 3,
    workload: 4,
    isExpanded: false,
    updates: [],
    subtasks: [
      {
        id: 301,
        parentId: 3,
        title: "Mobile layout design",
        description: "Design mobile-specific layouts",
        assigneeIds: [3],
        startDate: "2025-03-12",
        endDate: "2025-03-14",
        status: "in-progress",
        completion: 70,
      },
      {
        id: 302,
        parentId: 3,
        title: "Tablet layout design",
        description: "Design tablet-specific layouts",
        assigneeIds: [1],
        startDate: "2025-03-14",
        endDate: "2025-03-16",
        status: "pending",
        completion: 0,
      },
      {
        id: 303,
        parentId: 3,
        title: "Implementation and testing",
        description: "Implement responsive layouts and test across devices",
        assigneeIds: [1, 3],
        startDate: "2025-03-16",
        endDate: "2025-03-18",
        status: "pending",
        completion: 0,
      },
    ],
  },
  {
    id: 4,
    title: "CI/CD Pipeline Setup",
    description: "Set up continuous integration and deployment pipeline for the project.",
    assigneeIds: [5],
    startDate: "2025-03-09",
    endDate: "2025-03-13",
    status: "completed",
    completion: 100,
    complexity: 4,
    workload: 3,
    isExpanded: false,
    updates: [
      {
        id: 103,
        text: "Pipeline fully implemented and tested with all environments.",
        timestamp: "2025-03-13T16:45:00Z",
        userId: 5,
      },
    ],
  },
  {
    id: 5,
    title: "Project Planning",
    description: "Create project timeline, allocate resources, and define milestones.",
    assigneeIds: [4],
    startDate: "2025-03-05",
    endDate: "2025-03-12",
    status: "approved",
    completion: 100,
    complexity: 3,
    workload: 5,
    isExpanded: false,
    updates: [
      {
        id: 104,
        text: "Project plan approved by stakeholders.",
        timestamp: "2025-03-12T11:30:00Z",
        userId: 4,
      },
    ],
  },
  {
    id: 6,
    title: "Database Schema Design",
    description: "Design the database schema for the application.",
    assigneeIds: [2],
    startDate: "2025-03-06",
    endDate: "2025-03-09",
    status: "approved",
    completion: 100,
    complexity: 4,
    workload: 3,
    isExpanded: false,
    updates: [],
  },
  {
    id: 7,
    title: "User Testing Coordination",
    description: "Coordinate user testing sessions and collect feedback.",
    assigneeIds: [4, 1],
    startDate: "2025-03-15",
    endDate: "2025-03-20",
    status: "pending",
    completion: 0,
    complexity: 2,
    workload: 4,
    isExpanded: false,
    updates: [],
    subtasks: [
      {
        id: 701,
        parentId: 7,
        title: "Recruit test participants",
        description: "Find and schedule participants for testing sessions",
        assigneeIds: [1],
        startDate: "2025-03-15",
        endDate: "2025-03-17",
        status: "pending",
        completion: 0,
      },
      {
        id: 702,
        parentId: 7,
        title: "Prepare test scenarios",
        description: "Create test scripts and scenarios",
        assigneeIds: [4],
        startDate: "2025-03-16",
        endDate: "2025-03-18",
        status: "pending",
        completion: 0,
      },
      {
        id: 703,
        parentId: 7,
        title: "Conduct testing sessions",
        description: "Run user testing sessions and document feedback",
        assigneeIds: [4, 1],
        startDate: "2025-03-18",
        endDate: "2025-03-20",
        status: "pending",
        completion: 0,
      },
    ],
  },
  {
    id: 8,
    title: "Performance Optimization",
    description: "Optimize application performance and loading times.",
    assigneeIds: [1],
    startDate: "2025-03-19",
    endDate: "2025-03-25",
    status: "pending",
    completion: 0,
    complexity: 5,
    workload: 4,
    isExpanded: false,
    updates: [],
  },
]

// Current user for demo purposes
export const currentUser = staffMembers[4] // Manager by default
